[env]
TERM = "xterm-256color"

[font]
size = 16
normal.family ="MesloLGS Nerd Font Mono" 

[window]
padding.x = 10
padding.y = 10
opacity = 0.8
blur = true
startup_mode = "Maximized"
decorations = "Buttonless"
