[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "FiraCode Nerd Font"
style = "Medium"

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[window]
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 10
