import = [
  "~/.config/alacritty/themes/themes/monokai_charcoal.toml"
]
[env]
TERM = "xterm-256color"

[font]
size = 14
normal.family ="MesloLGS Nerd Font Mono" 

[window]
padding.x = 10
padding.y = 10
opacity = 0.7
blur = true
startup_mode = "Maximized"
decorations = "Buttonless"
